"""Bounded shared-memory transport for Orion's display-only preview.

The detector always consumes the original frame inside ``remote_play_orchestrator``.
This module only replaces the expensive JPEG/base64/stdout preview hop with one
latest-frame Windows mapping.  Negotiated native builds wake through a per-session
Windows auto-reset event; older builds retain the tiny JSONL notification fallback.

Wire layout (little endian, fixed 64-byte header)::

    uint32 magic              0x4f52464d ("ORFM")
    uint32 version            1
    uint32 width
    uint32 height
    uint32 channels           3 (BGR)
    uint32 source_frame_no    detector/decoder join identity
    uint64 timestamp_ns       producer monotonic timestamp
    uint64 write_count        monotonically increasing mapping identity
    uint8  reserved[24]
    uint8  bgr[width*height*3]

The mapping is deliberately capped at 1280x720 BGR.  Larger 16:9 preview frames
are aspect-preserving downscales; malformed channel/dtype inputs fail closed and
are never stretched.  A named mutex protects the one bulk copy.  Every publish
first invalidates the header, copies the full body, then commits a valid header.
Consequently a producer that dies while owning the mutex leaves an explicitly
invalid generation for the native reader to drop before clean recovery.
"""

from __future__ import annotations

import argparse
import logging
import mmap
import os
import re
import struct
import threading
import time
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)

MAPPING_NAME = "OrionPreviewFrame_v1"
MUTEX_NAME = "OrionPreviewMutex"
READY_EVENT_ENV = "ORION_PREVIEW_SHM_READY_EVENT"
MAPPING_ENV = "ORION_PREVIEW_SHM_MAPPING"
MUTEX_ENV = "ORION_PREVIEW_SHM_MUTEX"
MAGIC = 0x4F52464D
VERSION = 1
HEADER_SIZE = 64
HEADER_FMT = "<IIIIIIQQ"
HEADER_PACKED_SIZE = struct.calcsize(HEADER_FMT)
HEADER_PADDING = b"\x00" * (HEADER_SIZE - HEADER_PACKED_SIZE)
INVALID_HEADER = b"\x00" * HEADER_SIZE
MAX_WIDTH = 1280
MAX_HEIGHT = 720
CHANNELS = 3
MAX_BODY_SIZE = MAX_WIDTH * MAX_HEIGHT * CHANNELS
MAPPING_SIZE = HEADER_SIZE + MAX_BODY_SIZE

WAIT_OBJECT_0 = 0x00000000
WAIT_ABANDONED = 0x00000080
WAIT_TIMEOUT = 0x00000102
_KERNEL_OBJECT_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]{1,180}$")


def _kernel_object_name(value, fallback: str = "") -> str:
    """Accept only the narrow per-session names generated by OrionNative."""
    text = str(value or "").strip()
    return text if _KERNEL_OBJECT_NAME_RE.fullmatch(text) else fallback

if os.name == "nt":
    import ctypes
    import ctypes.wintypes

    _kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

    _CreateMutexW = _kernel32.CreateMutexW
    _CreateMutexW.restype = ctypes.wintypes.HANDLE
    _CreateMutexW.argtypes = [
        ctypes.c_void_p,
        ctypes.wintypes.BOOL,
        ctypes.wintypes.LPCWSTR,
    ]

    _CreateEventW = _kernel32.CreateEventW
    _CreateEventW.restype = ctypes.wintypes.HANDLE
    _CreateEventW.argtypes = [
        ctypes.c_void_p,
        ctypes.wintypes.BOOL,
        ctypes.wintypes.BOOL,
        ctypes.wintypes.LPCWSTR,
    ]

    _SetEvent = _kernel32.SetEvent
    _SetEvent.restype = ctypes.wintypes.BOOL
    _SetEvent.argtypes = [ctypes.wintypes.HANDLE]

    _WaitForSingleObject = _kernel32.WaitForSingleObject
    _WaitForSingleObject.restype = ctypes.wintypes.DWORD
    _WaitForSingleObject.argtypes = [
        ctypes.wintypes.HANDLE,
        ctypes.wintypes.DWORD,
    ]

    _ReleaseMutex = _kernel32.ReleaseMutex
    _ReleaseMutex.restype = ctypes.wintypes.BOOL
    _ReleaseMutex.argtypes = [ctypes.wintypes.HANDLE]

    _CloseHandle = _kernel32.CloseHandle
    _CloseHandle.restype = ctypes.wintypes.BOOL
    _CloseHandle.argtypes = [ctypes.wintypes.HANDLE]
else:  # pragma: no cover - exercised only by non-Windows development hosts
    _CreateMutexW = None
    _CreateEventW = None
    _SetEvent = None
    _WaitForSingleObject = None
    _ReleaseMutex = None
    _CloseHandle = None


class ShmFrameWriter:
    """Write the latest immutable BGR preview into a fixed Windows mapping."""

    def __init__(
        self,
        max_width: int = MAX_WIDTH,
        max_height: int = MAX_HEIGHT,
        mutex_timeout_ms: int = 3,
        mapping_name: Optional[str] = None,
        mutex_name: Optional[str] = None,
        ready_event_name: Optional[str] = None,
    ) -> None:
        # The native reader maps the fixed protocol size.  Do not silently create
        # an incompatible larger mapping from a caller-provided value.
        self._max_width = min(MAX_WIDTH, max(1, int(max_width)))
        self._max_height = min(MAX_HEIGHT, max(1, int(max_height)))
        self._max_body = MAX_BODY_SIZE
        self._total_size = MAPPING_SIZE
        self._mutex_timeout_ms = max(0, min(100, int(mutex_timeout_ms)))
        self._mapping_name = _kernel_object_name(
            mapping_name if mapping_name is not None else os.environ.get(MAPPING_ENV),
            MAPPING_NAME,
        )
        self._mutex_name = _kernel_object_name(
            mutex_name if mutex_name is not None else os.environ.get(MUTEX_ENV),
            MUTEX_NAME,
        )
        self._ready_event_name = _kernel_object_name(
            ready_event_name if ready_event_name is not None
            else os.environ.get(READY_EVENT_ENV),
            "",
        )
        self._mmap: Optional[mmap.mmap] = None
        self._mutex = None
        self._ready_event = None
        self._write_count = 0
        self._fallback_frame_number = 0
        self._enabled = False
        self._lock = threading.Lock()
        self._last_error = ""
        self._last_geometry = (0, 0)
        self._last_commit_ns = 0
        self._last_event_notify_ns = 0
        self._last_write_duration_ms = 0.0
        self._last_event_notify_ms = 0.0
        self._event_signal_failures = 0

    @property
    def enabled(self) -> bool:
        return self._enabled

    @property
    def last_error(self) -> str:
        return self._last_error

    @property
    def event_notifications_enabled(self) -> bool:
        return bool(self._ready_event)

    @property
    def last_commit_ns(self) -> int:
        return int(self._last_commit_ns)

    @property
    def last_event_notify_ns(self) -> int:
        return int(self._last_event_notify_ns)

    @property
    def last_write_duration_ms(self) -> float:
        return float(self._last_write_duration_ms)

    @property
    def last_event_notify_ms(self) -> float:
        return float(self._last_event_notify_ms)

    @property
    def event_signal_failures(self) -> int:
        return int(self._event_signal_failures)

    def start(self) -> bool:
        """Create/open the mapping and named mutex.  Never raises."""
        if os.name != "nt" or _CreateMutexW is None:
            self._last_error = "shared-memory preview is Windows-only"
            return False
        with self._lock:
            if self._enabled and self._mmap is not None and self._mutex:
                return True
            self._close_locked()
            try:
                self._mutex = _CreateMutexW(None, False, self._mutex_name)
                if not self._mutex:
                    self._last_error = "CreateMutexW failed"
                    return False
                # mmap(tagname=...) uses CreateFileMappingW internally and keeps
                # the section alive for this process.  ACCESS_WRITE permits the
                # native process to open the same section with FILE_MAP_READ.
                self._mmap = mmap.mmap(
                    -1,
                    self._total_size,
                    tagname=self._mapping_name,
                    access=mmap.ACCESS_WRITE,
                )
                if self._ready_event_name and _CreateEventW is not None:
                    # Auto-reset, initially non-signaled. OrionNative normally
                    # creates the same named event before launching this process.
                    self._ready_event = _CreateEventW(
                        None, False, False, self._ready_event_name)
                    if not self._ready_event:
                        logger.warning(
                            "SHM frame-ready event unavailable; using stdout fallback")
                self._enabled = True
                self._last_error = ""
                logger.info(
                    "SHM preview writer ready: mapping=%s bytes=%d max=%dx%d BGR",
                    self._mapping_name,
                    self._total_size,
                    self._max_width,
                    self._max_height,
                )
                return True
            except Exception as exc:
                self._last_error = f"mapping creation failed: {exc}"
                logger.warning("SHM preview writer start failed: %s", exc)
                self._close_locked()
                return False

    def _prepare_frame(self, frame: np.ndarray) -> Optional[np.ndarray]:
        if not isinstance(frame, np.ndarray):
            self._last_error = "frame is not a numpy array"
            return None
        if frame.dtype != np.uint8 or frame.ndim != 3 or frame.shape[2] != CHANNELS:
            self._last_error = "frame must be uint8 HxWx3 BGR"
            return None
        h, w = int(frame.shape[0]), int(frame.shape[1])
        if w <= 0 or h <= 0:
            self._last_error = "frame geometry is empty"
            return None
        if w > self._max_width or h > self._max_height:
            scale = min(self._max_width / float(w), self._max_height / float(h))
            new_w = max(1, int(round(w * scale)))
            new_h = max(1, int(round(h * scale)))
            # Preserve geometry; never independently stretch either axis.
            try:
                import cv2

                frame = cv2.resize(
                    frame,
                    (new_w, new_h),
                    interpolation=cv2.INTER_AREA,
                )
            except Exception as exc:
                self._last_error = f"preview resize failed: {exc}"
                return None
            h, w = new_h, new_w
        if w > MAX_WIDTH or h > MAX_HEIGHT or w * h * CHANNELS > MAX_BODY_SIZE:
            self._last_error = "frame exceeds fixed mapping bounds"
            return None
        if not frame.flags["C_CONTIGUOUS"]:
            frame = np.ascontiguousarray(frame)
        return frame

    def write(
        self,
        frame: np.ndarray,
        source_frame_number: int = 0,
        timestamp_ns: int = 0,
    ) -> bool:
        """Publish one frame, latest-wins.  Returns False on a bounded drop/fault."""
        if not self._enabled or self._mmap is None or not self._mutex:
            self._last_error = "writer is not active"
            return False
        prepared = self._prepare_frame(frame)
        if prepared is None:
            return False
        h, w = int(prepared.shape[0]), int(prepared.shape[1])
        body_size = w * h * CHANNELS
        try:
            requested = int(source_frame_number or 0)
        except (TypeError, ValueError, OverflowError):
            requested = 0
        if requested <= 0:
            self._fallback_frame_number += 1
            requested = self._fallback_frame_number
        requested &= 0xFFFFFFFF
        stamp = int(timestamp_ns or time.perf_counter_ns()) & 0xFFFFFFFFFFFFFFFF
        write_started_ns = time.perf_counter_ns()

        with self._lock:
            if not self._enabled or self._mmap is None or not self._mutex:
                self._last_error = "writer stopped during publish"
                return False
            wait_result = int(
                _WaitForSingleObject(self._mutex, self._mutex_timeout_ms)
            )
            if wait_result not in (WAIT_OBJECT_0, WAIT_ABANDONED):
                self._last_error = f"mutex busy/result={wait_result}"
                return False
            try:
                self._write_count += 1
                header = struct.pack(
                    HEADER_FMT,
                    MAGIC,
                    VERSION,
                    w,
                    h,
                    CHANNELS,
                    requested,
                    stamp,
                    self._write_count & 0xFFFFFFFFFFFFFFFF,
                )
                # Invalidate before touching pixels, then commit the complete
                # header last. If this process dies or a slice assignment fails
                # mid-copy, an abandoned mutex can never expose a stale valid
                # header paired with a partially overwritten body.
                self._mmap[:HEADER_SIZE] = INVALID_HEADER
                self._mmap[HEADER_SIZE : HEADER_SIZE + body_size] = (
                    memoryview(prepared).cast("B")
                )
                self._mmap[:HEADER_PACKED_SIZE] = header
                self._mmap[HEADER_PACKED_SIZE:HEADER_SIZE] = HEADER_PADDING
            except Exception as exc:
                self._last_error = f"mapping write failed: {exc}"
                logger.warning("SHM preview write failed: %s", exc)
                return False
            finally:
                if not _ReleaseMutex(self._mutex):
                    logger.warning("SHM preview ReleaseMutex failed")

            # Commit time is sampled immediately after releasing the mapping
            # mutex and BEFORE any event/stdout notification work. This is the
            # actual successful SHM transport cadence used by preview_stats.
            self._last_commit_ns = time.perf_counter_ns()
            self._last_write_duration_ms = (
                self._last_commit_ns - write_started_ns) / 1_000_000.0
            self._last_event_notify_ns = 0
            self._last_event_notify_ms = 0.0
            if self._ready_event:
                notify_started_ns = time.perf_counter_ns()
                if _SetEvent(self._ready_event):
                    self._last_event_notify_ns = time.perf_counter_ns()
                    self._last_event_notify_ms = (
                        self._last_event_notify_ns - notify_started_ns) / 1_000_000.0
                else:
                    self._event_signal_failures += 1
                    try:
                        _CloseHandle(self._ready_event)
                    finally:
                        self._ready_event = None
                    logger.warning(
                        "SHM frame-ready event signal failed; using stdout fallback")

        if (w, h) != self._last_geometry:
            logger.info("SHM preview geometry: %dx%d", w, h)
            self._last_geometry = (w, h)
        self._last_error = ""
        return True

    def _close_locked(self) -> None:
        self._enabled = False
        mapping, self._mmap = self._mmap, None
        mutex, self._mutex = self._mutex, None
        ready_event, self._ready_event = self._ready_event, None
        if mapping is not None:
            try:
                mapping.close()
            except Exception:
                pass
        if mutex and _CloseHandle is not None:
            try:
                _CloseHandle(mutex)
            except Exception:
                pass
        if ready_event and _CloseHandle is not None:
            try:
                _CloseHandle(ready_event)
            except Exception:
                pass

    def stop(self) -> None:
        """Close transport resources without racing an in-flight publish."""
        with self._lock:
            self._close_locked()

    def __enter__(self) -> "ShmFrameWriter":
        if not self.start():
            raise RuntimeError(self._last_error or "SHM writer failed to start")
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.stop()


def _probe_frame(blue: int = 17, green: int = 83, red: int = 211) -> np.ndarray:
    frame = np.empty((MAX_HEIGHT, MAX_WIDTH, CHANNELS), dtype=np.uint8)
    frame[:, :, 0] = int(blue) & 0xFF
    frame[:, :, 1] = int(green) & 0xFF
    frame[:, :, 2] = int(red) & 0xFF
    return frame


def _run_probe(hold_ms: int) -> int:
    """Synthetic producer used by the native cross-process interoperability test."""
    frame = _probe_frame()
    writer = ShmFrameWriter()
    if not writer.start():
        print(f"SHM_PROBE_ERROR {writer.last_error}", flush=True)
        return 2
    try:
        if not writer.write(frame, source_frame_number=4242):
            print(f"SHM_PROBE_ERROR {writer.last_error}", flush=True)
            return 3
        print("SHM_PROBE_READY", flush=True)
        time.sleep(max(0, int(hold_ms)) / 1000.0)
        return 0
    finally:
        writer.stop()


def _run_series_probe(
    frame_count: int, interval_ms: int, start_delay_ms: int, hold_ms: int
) -> int:
    """Continuously advance one mapping for lost-ready-event diagnostics."""
    writer = ShmFrameWriter()
    if not writer.start():
        print(f"SHM_PROBE_ERROR {writer.last_error}", flush=True)
        return 2
    try:
        print("SHM_PROBE_MAPPING_READY", flush=True)
        time.sleep(max(0, int(start_delay_ms)) / 1000.0)
        for index in range(max(1, int(frame_count))):
            frame = _probe_frame(17 + index, 83, 211)
            if not writer.write(frame, source_frame_number=5000 + index):
                print(f"SHM_PROBE_ERROR {writer.last_error}", flush=True)
                return 3
            time.sleep(max(0, int(interval_ms)) / 1000.0)
        print("SHM_PROBE_SERIES_READY", flush=True)
        time.sleep(max(0, int(hold_ms)) / 1000.0)
        return 0
    finally:
        writer.stop()


def _run_abandoned_probe(hold_ms: int) -> int:
    """Hold an invalid partial generation until the test terminates us."""
    writer = ShmFrameWriter()
    if not writer.start():
        print(f"SHM_PROBE_ERROR {writer.last_error}", flush=True)
        return 2
    clean = _probe_frame()
    if not writer.write(clean, source_frame_number=4241):
        print(f"SHM_PROBE_ERROR {writer.last_error}", flush=True)
        writer.stop()
        return 3

    # Leave the first frame's auto-reset event pending, then begin a second
    # publish and stop after invalidation + a partial body copy. The native test
    # kills this process while it owns the named mutex, producing WAIT_ABANDONED.
    wait_result = int(_WaitForSingleObject(writer._mutex, 1000))
    if wait_result not in (WAIT_OBJECT_0, WAIT_ABANDONED):
        print(f"SHM_PROBE_ERROR mutex result={wait_result}", flush=True)
        writer.stop()
        return 4
    writer._mmap[:HEADER_SIZE] = INVALID_HEADER
    partial = memoryview(_probe_frame(229, 31, 7)).cast("B")
    writer._mmap[HEADER_SIZE : HEADER_SIZE + 4096] = partial[:4096]
    print("SHM_PROBE_ABANDON_LOCKED", flush=True)
    time.sleep(max(1000, int(hold_ms)) / 1000.0)
    # The regression normally terminates us. Avoid publishing a synthetic clean
    # generation if it is run manually and reaches the end of its hold.
    os._exit(0)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Orion shared-memory preview bridge")
    parser.add_argument("--probe", action="store_true")
    parser.add_argument("--probe-series", action="store_true")
    parser.add_argument("--probe-abandon", action="store_true")
    parser.add_argument("--frames", type=int, default=120)
    parser.add_argument("--interval-ms", type=int, default=8)
    parser.add_argument("--start-delay-ms", type=int, default=750)
    parser.add_argument("--hold-ms", type=int, default=3000)
    args = parser.parse_args(argv)
    selected = int(args.probe) + int(args.probe_series) + int(args.probe_abandon)
    if selected > 1:
        parser.error("select exactly one probe mode")
    if args.probe:
        return _run_probe(args.hold_ms)
    if args.probe_series:
        return _run_series_probe(
            args.frames, args.interval_ms, args.start_delay_ms, args.hold_ms)
    if args.probe_abandon:
        return _run_abandoned_probe(args.hold_ms)
    parser.error("no operation selected")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
