#!/usr/bin/env python3
"""
generate_programs.py -- emit venice_programs_shuffled.h at build time.

The Venice VM's ``venice_programs.h`` carries hand-written bytecode blobs for
``VVM_PROG_DERIVE_KEY`` and ``VVM_PROG_SHARD_XOR`` encoded with the CANONICAL
opcode map. When ``VVM_SHUFFLE_OPCODES=ON`` (the default) the interpreter is
built to dispatch a per-build randomized map, so the canonical bytecode would
be misinterpreted and every packed binary would fail its first crypto call.

This generator closes that loop: it assembles the ``.vasm`` sources in
``programs/`` with the current build's shuffled opcode map and emits a
drop-in header exposing the same public symbols. ``venice_programs.h``
conditionally ``#include``s this file when ``VVM_SHUFFLED`` is defined.

Runs once per configure/build (CMake custom command; depends on the
shuffled-opcode file so a fresh shuffle triggers a re-assembly).

Usage:
    python generate_programs.py \\
        --shuffled-map venice_opcodes_shuffled.py \\
        --programs-dir programs \\
        --output venice_programs_shuffled.h
"""
from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path


# Public symbol names emitted by ``venice_programs.h``. Each maps to the
# ``.vasm`` source that replaces it under a shuffled opcode map. The list is
# deliberately explicit — silently emitting extra programs would drift from
# what venice_programs.h exposes.
PROGRAMS = [
    ("VVM_PROG_DERIVE_KEY", "derive_key.vasm"),
    ("VVM_PROG_SHARD_XOR",  "shard_xor.vasm"),
]


def _load_asm(venice_dir: Path):
    """Import venice_asm from the sibling dir (it's not an installed package)."""
    if str(venice_dir) not in sys.path:
        sys.path.insert(0, str(venice_dir))
    import venice_asm  # type: ignore
    return venice_asm


def _load_shuffled_map(path: Path):
    spec = importlib.util.spec_from_file_location("_vvm_shuffled", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod.SHUFFLED_OPCODES


def _assemble(vasm_path: Path, shuffled_map: dict, venice_asm) -> bytes:
    source = vasm_path.read_text(encoding="utf-8")
    # Swap the assembler's opcode table for the shuffled map, assemble, restore.
    saved = venice_asm.OPCODES
    venice_asm.OPCODES = shuffled_map
    try:
        blob = venice_asm.assemble(source)
    finally:
        venice_asm.OPCODES = saved
    return bytes(blob)


def _format_c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        row = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {row},")
    lines.append("};")
    lines.append(f"static const uint32_t {name}_SIZE = sizeof({name});")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--shuffled-map", required=True, type=Path,
                    help="Path to venice_opcodes_shuffled.py")
    ap.add_argument("--programs-dir", required=True, type=Path,
                    help="Directory containing the .vasm source programs")
    ap.add_argument("--output", required=True, type=Path,
                    help="Path to write venice_programs_shuffled.h")
    args = ap.parse_args()

    venice_dir = Path(__file__).resolve().parent
    venice_asm = _load_asm(venice_dir)
    shuffled_map = _load_shuffled_map(args.shuffled_map)

    header = [
        "/* venice_programs_shuffled.h -- generated by generate_programs.py.",
        " *",
        " * DO NOT EDIT. Re-emitted on every build with the shuffled opcode map.",
        " * If VVM_SHUFFLE_OPCODES is OFF, this file is not included; the",
        " * hand-written canonical bytecode in venice_programs.h is used instead.",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]

    for sym, filename in PROGRAMS:
        vasm_path = args.programs_dir / filename
        if not vasm_path.is_file():
            print(f"error: {vasm_path} not found", file=sys.stderr)
            return 1
        blob = _assemble(vasm_path, shuffled_map, venice_asm)
        header.append(f"/* {sym}: assembled from {filename} ({len(blob)} bytes) */")
        header.append(_format_c_array(sym, blob))
        header.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(header), encoding="utf-8")
    print(f"generate_programs: wrote {args.output} "
          f"({len(PROGRAMS)} programs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
