"""
venice_opcodes_shuffled.py
Auto-generated by shuffle_opcodes.py -- DO NOT EDIT
Build seed: 06b77204c4ba0372bed89c1c011112aa1f303553959d6ff14ceb3eea62c452f4
"""

# Shuffled opcode table: mnemonic -> (wire_byte, operand_width, operand_kind)
# Drop-in replacement for venice_asm.OPCODES with per-build wire bytes.
SHUFFLED_OPCODES = {
    'halt'          : (0xF8, 0, 'none'),
    'nop'           : (0x73, 0, 'none'),
    'push_imm8'     : (0xA3, 1, 'imm'),
    'push_imm32'    : (0x49, 4, 'imm'),
    'push_imm64'    : (0x32, 8, 'imm'),
    'pop'           : (0x71, 0, 'none'),
    'dup'           : (0x0C, 0, 'none'),
    'swap'          : (0xD6, 0, 'none'),
    'add'           : (0x6F, 0, 'none'),
    'sub'           : (0x9A, 0, 'none'),
    'xor'           : (0x1D, 0, 'none'),
    'and'           : (0x2A, 0, 'none'),
    'or'            : (0xC1, 0, 'none'),
    'shl'           : (0x7D, 0, 'none'),
    'shr'           : (0xB8, 0, 'none'),
    'mul'           : (0xFB, 0, 'none'),
    'load8'         : (0x35, 0, 'none'),
    'load32'        : (0x08, 0, 'none'),
    'load64'        : (0x36, 0, 'none'),
    'store8'        : (0xA9, 0, 'none'),
    'store32'       : (0x28, 0, 'none'),
    'store64'       : (0x3C, 0, 'none'),
    'cmp_eq'        : (0xC0, 0, 'none'),
    'cmp_lt'        : (0xA6, 0, 'none'),
    'jmp'           : (0x39, 4, 'label'),
    'jz'            : (0xDD, 4, 'label'),
    'jnz'           : (0xF1, 4, 'label'),
    'call'          : (0x8C, 4, 'label'),
    'push_arg'      : (0xAB, 1, 'imm'),
    'local_addr'    : (0x79, 2, 'imm'),
    'data_addr'     : (0x3E, 2, 'imm'),
    'ret'           : (0x65, 0, 'none'),
    'n_sha256'      : (0x04, 0, 'none'),
    'n_hkdf'        : (0x97, 0, 'none'),
    'n_xor_buf'     : (0x6B, 0, 'none'),
    'n_getenv'      : (0xFD, 0, 'none'),
    'n_setenv_null' : (0x5D, 0, 'none'),
    'n_hex_decode'  : (0xB1, 0, 'none'),
    'n_zero_mem'    : (0x57, 0, 'none'),
    'n_scatter_init': (0x96, 0, 'none'),
    'n_copy_mem'    : (0xBD, 0, 'none'),
    'n_xor_repeat'  : (0x99, 0, 'none'),
    'n_xor_const'   : (0xA0, 0, 'none'),
    'n_call_ptr'    : (0x4C, 0, 'none'),
    'div'           : (0xE6, 0, 'none'),
    'mod'           : (0x21, 0, 'none'),
    'neg'           : (0xA2, 0, 'none'),
    'not'           : (0x63, 0, 'none'),
    'cmp_gt'        : (0xAA, 0, 'none'),
    'cmp_ge'        : (0x56, 0, 'none'),
    'cmp_ne'        : (0xDE, 0, 'none'),
    'push_imm16'    : (0x3A, 2, 'imm'),
    'load16'        : (0x1A, 0, 'none'),
    'store16'       : (0xA1, 0, 'none'),
    'rot3'          : (0xC3, 0, 'none'),
    'pick'          : (0x33, 1, 'imm'),
}

# Decoy wire bytes (single-byte no-op instructions for noise insertion)
DECOY_WIRE_BYTES = [0xE7, 0x40, 0x84, 0x77, 0x90, 0x15, 0x2E, 0x94, 0x8F, 0x06, 0x19, 0x42, 0x1E, 0x7E, 0x78, 0x0A, 0x46]

# Fraction of real instructions to pad with randomly-inserted decoy bytes
NOISE_RATIO = 0.15

# Reproducible build seed (hex)
BUILD_SEED = '06b77204c4ba0372bed89c1c011112aa1f303553959d6ff14ceb3eea62c452f4'

