#pragma once
#include <stdint.h>

/*
 * venice_programs.h -- Venice VM bytecode for the two critical crypto paths.
 *
 * TWO source-of-truth modes, selected at build time by ``VVM_SHUFFLED``:
 *
 *   * VVM_SHUFFLED DEFINED (default: ON via CMake VVM_SHUFFLE_OPCODES):
 *     the bytecode below is not used. We include the build-time generated
 *     ``venice_programs_shuffled.h`` which was assembled from the ``.vasm``
 *     sources in ``venice/programs/`` against THIS build's shuffled opcode
 *     map. The two must move together: the interpreter dispatches shuffled
 *     wire bytes, and this bytecode is encoded to match.
 *
 *   * VVM_SHUFFLED NOT DEFINED (VVM_SHUFFLE_OPCODES=OFF at configure time):
 *     the hand-written CANONICAL bytecode below is used. Kept as a fallback
 *     and as the reference implementation the assembler cross-checks against.
 *
 * If you edit the canonical bytecode: modify the assembly listing in the
 * comments and re-encode, then re-verify every JMP/JZ/JNZ target by counting
 * bytes from code offset 0. If you edit a ``.vasm`` source: nothing else to do
 * -- CMake regenerates the shuffled header on the next build.
 */

#ifdef VVM_SHUFFLED
/* Shuffled build: use the per-build-generated bytecode. This header defines
 * VVM_PROG_DERIVE_KEY / VVM_PROG_SHARD_XOR and their _SIZE counterparts using
 * the shuffled wire bytes so the interpreter's decode agrees with them. */
#  include "venice_programs_shuffled.h"
#else
/* Canonical (unshuffled) bytecode -- reference implementation.
 *
 * Generated BY HAND from the C source logic (crypto_derive_key in crypto.c and
 * the ORION_SHARD block in pe_loader.c). DO NOT edit the byte arrays directly --
 * modify the assembly listing in the comments and re-encode, then re-verify
 * every JMP/JZ/JNZ target by counting bytes from code offset 0.
 *
 * ---- Program blob layout (consumed by venice_vm_exec) --------------------
 *   u16 data_size   (little-endian)
 *   u8  data[data_size]
 *   u8  code[]       (runs to end of blob)
 * The array below is the WHOLE blob (header + data + code); *_SIZE is sizeof().
 *
 * ---- ISA / encoding assumptions this bytecode relies on ------------------
 * These must hold in venice_vm.c (built in parallel). If any differs, the byte
 * offsets / operands below must be regenerated.
 *   1. Branch operands (JMP/JZ/JNZ, +4 LE) are ABSOLUTE byte offsets into the
 *      code section, i.e. code[0] == offset 0 (per "count bytes from offset 0").
 *   2. JZ pops TOS and branches when it is zero; JNZ pops TOS and branches when
 *      it is nonzero. Both consume the tested value.
 *   3. Native ops pop their arguments (pushed LEFT-TO-RIGHT: first arg pushed
 *      first) and push the documented result (0/1 or DWORD) or nothing (void).
 *   4. LOCAL_ADDR off (+2 LE) pushes the absolute address of the VM local frame
 *      byte at `off`; DATA_ADDR off (+2 LE) pushes &data[off]. The local frame
 *      must be >= 76 bytes for DERIVE_KEY and >= 49 bytes for SHARD_XOR.
 *   5. Struct field offsets that have bit7 set as a byte (112/144/160/164) are
 *      pushed with PUSH_IMM32 (bit31 clear) so the value is identical whether
 *      the VM sign- or zero-extends immediates. Every PUSH_IMM8 used here is
 *      <= 0x7F (extension-immaterial), except the XOR byte 0xA5 whose only use
 *      is N_XOR_CONST's byte_val (low 8 bits only).
 *
 * Opcode quick ref (see task ISA):
 *   HALT=0x00 PUSH_IMM8=0x02(+1) PUSH_IMM32=0x03(+4) ADD=0x08 LOAD32=0x11
 *   CMP_EQ=0x16 JZ=0x19(+4) JNZ=0x1A(+4) PUSH_ARG=0x1C(+1)
 *   LOCAL_ADDR=0x1D(+2) DATA_ADDR=0x1E(+2)
 *   N_SHA256=0x20 N_HKDF=0x21 N_XOR_BUF=0x22 N_GETENV=0x23 N_SETENV_NULL=0x24
 *   N_HEX_DECODE=0x25 N_ZERO_MEM=0x26 N_COPY_MEM=0x28 N_XOR_REPEAT=0x29
 *   N_XOR_CONST=0x2A
 */

/* =========================================================================
 * PROGRAM 1: VVM_PROG_DERIVE_KEY  -- replaces crypto_derive_key()
 *
 *   args[0] = pi          (const PackInfo *)
 *   args[1] = image_base  (const void *)
 *   args[2] = out_key     (uint8_t[32])
 *   locals: [0..31] digest   [32..63] mask   [64..75] info ("OrionPack-v1")
 *   data:   [0..11] info_enc = "OrionPack-v1" XOR 0xA5
 *
 * PackInfo offsets used: stub_text_rva=160  stub_text_size=164
 *                        kdf_salt=144       aes_key_enc=112
 *
 * ; off   bytes                 instruction        ; effect
 * ; ----  --------------------  -----------------  ; --------------------------
 * ; 0x00  1D 40 00              LOCAL_ADDR 64      ; &info               (dst)
 * ; 0x03  1E 00 00              DATA_ADDR 0        ; &info_enc           (src)
 * ; 0x06  02 0C                 PUSH_IMM8 12       ; len
 * ; 0x08  28                    N_COPY_MEM         ; info = info_enc
 * ; 0x09  1D 40 00              LOCAL_ADDR 64      ; &info               (buf)
 * ; 0x0C  02 0C                 PUSH_IMM8 12       ; len
 * ; 0x0E  02 A5                 PUSH_IMM8 0xA5     ; byte_val
 * ; 0x10  2A                    N_XOR_CONST        ; info ^= 0xA5  -> "OrionPack-v1"
 * ; 0x11  1C 01                 PUSH_ARG 1         ; image_base
 * ; 0x13  1C 00                 PUSH_ARG 0         ; pi
 * ; 0x15  03 A0 00 00 00        PUSH_IMM32 160     ; off stub_text_rva
 * ; 0x1A  08                    ADD                ; pi+160
 * ; 0x1B  11                    LOAD32             ; stub_text_rva
 * ; 0x1C  08                    ADD                ; text_ptr = image_base+rva
 * ; 0x1D  1C 00                 PUSH_ARG 0         ; pi
 * ; 0x1F  03 A4 00 00 00        PUSH_IMM32 164     ; off stub_text_size
 * ; 0x24  08                    ADD                ; pi+164
 * ; 0x25  11                    LOAD32             ; text_size
 * ; 0x26  1D 00 00              LOCAL_ADDR 0       ; &digest             (out)
 * ; 0x29  20                    N_SHA256           ; -> 0/1
 * ; 0x2A  1A 67 00 00 00        JNZ 0x67           ; sha failed -> error
 * ; 0x2F  1D 00 00              LOCAL_ADDR 0       ; ikm = &digest
 * ; 0x32  02 20                 PUSH_IMM8 32       ; ikm_len
 * ; 0x34  1C 00                 PUSH_ARG 0         ; pi
 * ; 0x36  03 90 00 00 00        PUSH_IMM32 144     ; off kdf_salt
 * ; 0x3B  08                    ADD                ; salt = pi+144
 * ; 0x3C  02 10                 PUSH_IMM8 16       ; salt_len
 * ; 0x3E  1D 40 00              LOCAL_ADDR 64      ; info = &info
 * ; 0x41  02 0C                 PUSH_IMM8 12       ; info_len
 * ; 0x43  1D 20 00              LOCAL_ADDR 32      ; out = &mask
 * ; 0x46  02 20                 PUSH_IMM8 32       ; out_len
 * ; 0x48  21                    N_HKDF             ; -> 0/1  (mask filled)
 * ; 0x49  1A 67 00 00 00        JNZ 0x67           ; hkdf failed -> error
 * ; 0x4E  1C 02                 PUSH_ARG 2         ; dst = out_key
 * ; 0x50  1C 00                 PUSH_ARG 0         ; pi
 * ; 0x52  03 70 00 00 00        PUSH_IMM32 112     ; off aes_key_enc
 * ; 0x57  08                    ADD                ; src_a = pi+112
 * ; 0x58  1D 20 00              LOCAL_ADDR 32      ; src_b = &mask
 * ; 0x5B  02 20                 PUSH_IMM8 32       ; len
 * ; 0x5D  22                    N_XOR_BUF          ; out_key = aes_key_enc ^ mask
 * ; 0x5E  1D 00 00              LOCAL_ADDR 0       ; ptr = &digest
 * ; 0x61  02 4C                 PUSH_IMM8 76       ; len (digest+mask+info)
 * ; 0x63  26                    N_ZERO_MEM         ; wipe temporaries
 * ; 0x64  02 00                 PUSH_IMM8 0        ; success
 * ; 0x66  00                    HALT               ; return 0
 * ; ---- error path (target of both JNZ) at 0x67 ----
 * ; 0x67  1D 00 00              LOCAL_ADDR 0       ; ptr = &digest
 * ; 0x6A  02 4C                 PUSH_IMM8 76       ; len
 * ; 0x6C  26                    N_ZERO_MEM         ; wipe temporaries
 * ; 0x6D  02 01                 PUSH_IMM8 1        ; failure
 * ; 0x6F  00                    HALT               ; return 1
 * ; code size = 0x70 (112 bytes)
 * =======================================================================*/
static const uint8_t VVM_PROG_DERIVE_KEY[] = {
    /* header: data_size = 12 (u16 LE) */
    0x0C, 0x00,
    /* data[0..11]: info_enc = codehash_label XOR 0xA5 */
    0x2F, 0x99, 0xA4, 0x52, 0x37, 0x10, 0xC8, 0x41, 0xB4, 0xAF, 0xDA, 0xF6,
    /* code */
    /* 0x00 */ 0x1D, 0x40, 0x00,
    /* 0x03 */ 0x1E, 0x00, 0x00,
    /* 0x06 */ 0x02, 0x0C,
    /* 0x08 */ 0x28,
    /* 0x09 */ 0x1D, 0x40, 0x00,
    /* 0x0C */ 0x02, 0x0C,
    /* 0x0E */ 0x02, 0xA5,
    /* 0x10 */ 0x2A,
    /* 0x11 */ 0x1C, 0x01,
    /* 0x13 */ 0x1C, 0x00,
    /* 0x15 */ 0x03, 0xA0, 0x00, 0x00, 0x00,
    /* 0x1A */ 0x08,
    /* 0x1B */ 0x11,
    /* 0x1C */ 0x08,
    /* 0x1D */ 0x1C, 0x00,
    /* 0x1F */ 0x03, 0xA4, 0x00, 0x00, 0x00,
    /* 0x24 */ 0x08,
    /* 0x25 */ 0x11,
    /* 0x26 */ 0x1D, 0x00, 0x00,
    /* 0x29 */ 0x20,
    /* 0x2A */ 0x1A, 0x67, 0x00, 0x00, 0x00,
    /* 0x2F */ 0x1D, 0x00, 0x00,
    /* 0x32 */ 0x02, 0x20,
    /* 0x34 */ 0x1C, 0x00,
    /* 0x36 */ 0x03, 0x90, 0x00, 0x00, 0x00,
    /* 0x3B */ 0x08,
    /* 0x3C */ 0x02, 0x10,
    /* 0x3E */ 0x1D, 0x40, 0x00,
    /* 0x41 */ 0x02, 0x0C,
    /* 0x43 */ 0x1D, 0x20, 0x00,
    /* 0x46 */ 0x02, 0x20,
    /* 0x48 */ 0x21,
    /* 0x49 */ 0x1A, 0x67, 0x00, 0x00, 0x00,
    /* 0x4E */ 0x1C, 0x02,
    /* 0x50 */ 0x1C, 0x00,
    /* 0x52 */ 0x03, 0x70, 0x00, 0x00, 0x00,
    /* 0x57 */ 0x08,
    /* 0x58 */ 0x1D, 0x20, 0x00,
    /* 0x5B */ 0x02, 0x20,
    /* 0x5D */ 0x22,
    /* 0x5E */ 0x1D, 0x00, 0x00,
    /* 0x61 */ 0x02, 0x4C,
    /* 0x63 */ 0x26,
    /* 0x64 */ 0x02, 0x00,
    /* 0x66 */ 0x00,
    /* 0x67 */ 0x1D, 0x00, 0x00,
    /* 0x6A */ 0x02, 0x4C,
    /* 0x6C */ 0x26,
    /* 0x6D */ 0x02, 0x01,
    /* 0x6F */ 0x00,
};
static const uint32_t VVM_PROG_DERIVE_KEY_SIZE = sizeof(VVM_PROG_DERIVE_KEY);

/* =========================================================================
 * PROGRAM 2: VVM_PROG_SHARD_XOR  -- replaces the shard block in pe_loader.c
 *
 *   args[0] = key   (uint8_t[32], XOR'd in place)
 *   locals: [0..64] shex (65-byte env buffer)   [65..96] shard (32 bytes)
 *   data:   [0..11] "NV_RT_GATE\0\0"
 *
 * ; off   bytes                 instruction        ; effect
 * ; ----  --------------------  -----------------  ; --------------------------
 * ; 0x00  1E 00 00              DATA_ADDR 0        ; name = &"NV_RT_GATE"
 * ; 0x03  1D 00 00              LOCAL_ADDR 0       ; buf = &shex
 * ; 0x06  02 41                 PUSH_IMM8 65       ; bufsize (sizeof shex)
 * ; 0x08  23                    N_GETENV           ; -> len (DWORD)
 * ; 0x09  02 40                 PUSH_IMM8 64       ; 64
 * ; 0x0B  16                    CMP_EQ             ; (len == 64) ? 1 : 0
 * ; 0x0C  19 2E 00 00 00        JZ 0x2E            ; not 64 -> done (no shard)
 * ; 0x11  1D 00 00              LOCAL_ADDR 0       ; hex = &shex
 * ; 0x14  02 40                 PUSH_IMM8 64       ; hex_len
 * ; 0x16  1D 41 00              LOCAL_ADDR 65      ; out = &shard
 * ; 0x19  25                    N_HEX_DECODE       ; shard = unhex(shex)
 * ; 0x1A  1C 00                 PUSH_ARG 0         ; dst = key
 * ; 0x1C  1D 41 00              LOCAL_ADDR 65      ; src = &shard
 * ; 0x1F  02 20                 PUSH_IMM8 32       ; repeat_len = shard_len
 * ; 0x21  02 20                 PUSH_IMM8 32       ; total_len
 * ; 0x23  29                    N_XOR_REPEAT       ; key[i] ^= shard[i] (1:1)
 * ; 0x24  1E 00 00              DATA_ADDR 0        ; name
 * ; 0x27  24                    N_SETENV_NULL      ; unset NV_RT_GATE
 * ; 0x28  1D 00 00              LOCAL_ADDR 0       ; ptr = &shex
 * ; 0x2B  02 61                 PUSH_IMM8 97       ; len (shex+shard)
 * ; 0x2D  26                    N_ZERO_MEM         ; wipe locals
 * ; ---- done (target of JZ) at 0x2E ----
 * ; 0x2E  02 00                 PUSH_IMM8 0        ; success
 * ; 0x30  00                    HALT               ; return 0
 * ; code size = 0x31 (49 bytes)
 * =======================================================================*/
static const uint8_t VVM_PROG_SHARD_XOR[] = {
    /* header: data_size = 12 (u16 LE) */
    0x0C, 0x00,
    /* data[0..11]: "NV_RT_GATE\0\0" */
    0x4E, 0x56, 0x5F, 0x52, 0x54, 0x5F, 0x47, 0x41, 0x54, 0x45, 0x00, 0x00,
    /* code */
    /* 0x00 */ 0x1E, 0x00, 0x00,
    /* 0x03 */ 0x1D, 0x00, 0x00,
    /* 0x06 */ 0x02, 0x41,
    /* 0x08 */ 0x23,
    /* 0x09 */ 0x02, 0x40,
    /* 0x0B */ 0x16,
    /* 0x0C */ 0x19, 0x2E, 0x00, 0x00, 0x00,
    /* 0x11 */ 0x1D, 0x00, 0x00,
    /* 0x14 */ 0x02, 0x40,
    /* 0x16 */ 0x1D, 0x41, 0x00,
    /* 0x19 */ 0x25,
    /* 0x1A */ 0x1C, 0x00,
    /* 0x1C */ 0x1D, 0x41, 0x00,
    /* 0x1F */ 0x02, 0x20,
    /* 0x21 */ 0x02, 0x20,
    /* 0x23 */ 0x29,
    /* 0x24 */ 0x1E, 0x00, 0x00,
    /* 0x27 */ 0x24,
    /* 0x28 */ 0x1D, 0x00, 0x00,
    /* 0x2B */ 0x02, 0x61,
    /* 0x2D */ 0x26,
    /* 0x2E */ 0x02, 0x00,
    /* 0x30 */ 0x00,
};
static const uint32_t VVM_PROG_SHARD_XOR_SIZE = sizeof(VVM_PROG_SHARD_XOR);

#endif /* !VVM_SHUFFLED */
